language: ruby
services:
  - docker

cache:
  directories:
    - $HOME/docker

matrix:
  include:
   - arch: amd64
     env: PLATFORM="x86_64"
   - arch: amd64
     env: PLATFORM="i686"
   - arch: arm64
     env: PLATFORM="arm64v8"
   - arch: ppc64le
     env: PLATFORM="ppc64le"
   - arch: s390x
     env: PLATFORM="s390x"

script:
  - echo $PLATFORM; echo `dpkg --print-architecture`

#deploy:
#  skip_cleanup: true
#  provider: script
#  script: bash ./deploy.sh
#  on:
#    branch: xenial
